/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RostersIndexRouteImport } from './routes/rosters.index'
import { Route as PredictionsIndexRouteImport } from './routes/predictions.index'
import { Route as RostersSlugRouteImport } from './routes/rosters.$slug'
import { Route as PredictionsSlugRouteImport } from './routes/predictions.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RostersIndexRoute = RostersIndexRouteImport.update({
  id: '/rosters/',
  path: '/rosters/',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsIndexRoute = PredictionsIndexRouteImport.update({
  id: '/predictions/',
  path: '/predictions/',
  getParentRoute: () => rootRouteImport,
} as any)
const RostersSlugRoute = RostersSlugRouteImport.update({
  id: '/rosters/$slug',
  path: '/rosters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsSlugRoute = PredictionsSlugRouteImport.update({
  id: '/predictions/$slug',
  path: '/predictions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/predictions/$slug': typeof PredictionsSlugRoute
  '/rosters/$slug': typeof RostersSlugRoute
  '/predictions': typeof PredictionsIndexRoute
  '/rosters': typeof RostersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/predictions/$slug': typeof PredictionsSlugRoute
  '/rosters/$slug': typeof RostersSlugRoute
  '/predictions': typeof PredictionsIndexRoute
  '/rosters': typeof RostersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/predictions/$slug': typeof PredictionsSlugRoute
  '/rosters/$slug': typeof RostersSlugRoute
  '/predictions/': typeof PredictionsIndexRoute
  '/rosters/': typeof RostersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/predictions/$slug'
    | '/rosters/$slug'
    | '/predictions'
    | '/rosters'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/predictions/$slug'
    | '/rosters/$slug'
    | '/predictions'
    | '/rosters'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/predictions/$slug'
    | '/rosters/$slug'
    | '/predictions/'
    | '/rosters/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  PredictionsSlugRoute: typeof PredictionsSlugRoute
  RostersSlugRoute: typeof RostersSlugRoute
  PredictionsIndexRoute: typeof PredictionsIndexRoute
  RostersIndexRoute: typeof RostersIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rosters/': {
      id: '/rosters/'
      path: '/rosters'
      fullPath: '/rosters'
      preLoaderRoute: typeof RostersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions/': {
      id: '/predictions/'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rosters/$slug': {
      id: '/rosters/$slug'
      path: '/rosters/$slug'
      fullPath: '/rosters/$slug'
      preLoaderRoute: typeof RostersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions/$slug': {
      id: '/predictions/$slug'
      path: '/predictions/$slug'
      fullPath: '/predictions/$slug'
      preLoaderRoute: typeof PredictionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  PredictionsSlugRoute: PredictionsSlugRoute,
  RostersSlugRoute: RostersSlugRoute,
  PredictionsIndexRoute: PredictionsIndexRoute,
  RostersIndexRoute: RostersIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
