/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PredictionsIndexRouteImport } from './routes/predictions.index'
import { Route as RosterSlugRouteImport } from './routes/roster.$slug'
import { Route as PredictionsSlugRouteImport } from './routes/predictions.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsIndexRoute = PredictionsIndexRouteImport.update({
  id: '/predictions/',
  path: '/predictions/',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterSlugRoute = RosterSlugRouteImport.update({
  id: '/roster/$slug',
  path: '/roster/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsSlugRoute = PredictionsSlugRouteImport.update({
  id: '/predictions/$slug',
  path: '/predictions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/predictions/$slug': typeof PredictionsSlugRoute
  '/roster/$slug': typeof RosterSlugRoute
  '/predictions': typeof PredictionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/predictions/$slug': typeof PredictionsSlugRoute
  '/roster/$slug': typeof RosterSlugRoute
  '/predictions': typeof PredictionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/predictions/$slug': typeof PredictionsSlugRoute
  '/roster/$slug': typeof RosterSlugRoute
  '/predictions/': typeof PredictionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/predictions/$slug'
    | '/roster/$slug'
    | '/predictions'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/predictions/$slug'
    | '/roster/$slug'
    | '/predictions'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/predictions/$slug'
    | '/roster/$slug'
    | '/predictions/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PredictionsSlugRoute: typeof PredictionsSlugRoute
  RosterSlugRoute: typeof RosterSlugRoute
  PredictionsIndexRoute: typeof PredictionsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions/': {
      id: '/predictions/'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/$slug': {
      id: '/roster/$slug'
      path: '/roster/$slug'
      fullPath: '/roster/$slug'
      preLoaderRoute: typeof RosterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions/$slug': {
      id: '/predictions/$slug'
      path: '/predictions/$slug'
      fullPath: '/predictions/$slug'
      preLoaderRoute: typeof PredictionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PredictionsSlugRoute: PredictionsSlugRoute,
  RosterSlugRoute: RosterSlugRoute,
  PredictionsIndexRoute: PredictionsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
